# Generated by Django 4.2.6 on 2023-10-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_content_alter_comment_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='star',
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
